### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by swelborn** [NERSC/interactEM#54]
# Nice to have next steps
- [ ] #83
- [ ] #85
- [x] #89

# Complete
- [x] Propagate errors back to the client #55 
- [x] License: MIT/BSD #64 
- [x] Dockerfile re-organization (base image, better caching) #59 
- [x] Dockerfile labels #75 
- [x] One-liner for operator, so we avoid `if __name__ == "__main__":` #62 
- [x] zod validation
- [x] #57 
- [x] #86
- [x] setup admin database account
- [x] Give distiller-dev ❤ 
- [x] #91
- [x] nats cert
- [x] #90
- [x] #104
- [x] #76 
- [x] Setup agent at NCEM
- [x] build/pull podman containers on perlmutter
- [x] #84
- [x] #77 
- [x] #99 
- [x] #101 
- [x] #87
